name: arch_explain
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  dartz: ^0.10.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  logger: ^1.1.0

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  lint: ^1.8.2

flutter:
  uses-material-design: true
